url: "http://www.chaona.net" # the base hostname & protocol for your site, e.g. http://example.com

# url标准化
permalink: /:categories/:title.html

gems:
  - jekyll-sitemap

# 分页
paginate: 15
paginate_path: "blog/page:num"

subtitle: "ChaoNa.net"